services:
  postgres-db:
    build: ./postgres-db
    container_name: its-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    networks:
      - its_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost"]
      start_period: 1s
      interval: 2s
      timeout: 1s
      retries: 5

  identity:
    build:
      context: ./identity-service
    container_name: identity-service
    volumes:
    - ./identity-service/internal:/app/internal:ro
    env_file:
      - .env
    ports:
      - "127.0.0.1:${IDENTITY_SVC_PORT}:${IDENTITY_SVC_PORT}"
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - its_network
    # healthcheck:
    #   test: ["CMD", "/app/identity-service", "health"]
    #   start_period: 10s
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  course:
    build: 
      context: ./course-service
    container_name: course-service
    volumes:
      - ./course-service/src:/app/src:ro
    env_file:
      - .env
    ports:
      - "127.0.0.1:${COURSE_SVC_PORT}:${COURSE_SVC_PORT}"
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - its_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${COURSE_SVC_PORT}/actuator/health"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
   
volumes:
  postgres_data:
networks:
  its_network:
    driver: bridge
